name: CI/CD - Build and Deploy to EKS

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build JAR with Maven
      run: mvn clean package --file pom.xml

    - name: Log in to Amazon ECR Public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public
      env:
        AWS_REGION: us-east-1

    - name: Build and push Docker image
      run: |
        IMAGE_URI=${{ secrets.ECR_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        
    - name: Get Ingress and Services Info   # 👈 ADD THIS HERE
      run: |
        kubectl get ingress
        kubectl get svc -n ingress-nginx
        kubectl get pods -n ingress-nginx
