name: CI/CD - Deploy to EKS

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: latest

jobs:
  deploy-only:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Apply aws-auth ConfigMap (node access)
      run: |
        kubectl apply -f k8s/aws-auth.yaml
        
    - name: Verify cluster connection
      run: kubectl get nodes

    - name: Deploy to EKS
      run: |
        kubectl apply --validate=false -f k8s/deployment.yaml
        kubectl apply --validate=false -f k8s/service.yaml
        kubectl apply --validate=false -f k8s/ingress.yaml

    - name: Get Ingress and Services Info
      run: |
        kubectl get ingress
        kubectl get svc -n ingress-nginx
        kubectl get pods -n ingress-nginx
