name: Build and Test Java App in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build JAR with Maven
      run: mvn clean package --no-transfer-progress

    - name: Build Docker image
      run: docker build -t java-middleware .

    - name: Test Docker container
      run: |
        docker run -d -p 9090:9090 --name test-app java-middleware
        sleep 10

    - name: Show logs (to debug exit/crash)
    
    - name: Test endpoint inside container
      run: docker exec test-app curl -f http://localhost:9090/hello
