name: Build and Push to AWS Public ECR

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  IMAGE_NAME: middleware-service
  PUBLIC_ECR_URI: public.ecr.aws/m1u8i8e9/middleware-service/middleware-serviceone

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin' 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to AWS Public ECR
      run: |
        aws ecr-public get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin public.ecr.aws

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Tag image for public ECR
      run: docker tag $IMAGE_NAME:latest $PUBLIC_ECR_URI:latest

    - name: Push to AWS Public ECR
      run: docker push $PUBLIC_ECR_URI:latest
